language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - XDEBUG_MODE=coverage

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls build/logs/clover.xml